version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: things-app
    volumes: 
      - ./:/var/www/html
    ports:
      - 4000:4000
    network_mode: "host"
